// <auto-generated />
using AFCitizen.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AFCitizen.Migrations.FirstLevelDb
{
    [DbContext(typeof(FirstLevelDbContext))]
    [Migration("20190630043832_FirstLevelDB")]
    partial class FirstLevelDB
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AFCitizen.Models.Block", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AuthorityType");

                    b.Property<string>("City");

                    b.Property<string>("DocId");

                    b.Property<string>("Document");

                    b.Property<string>("From");

                    b.Property<string>("Hash");

                    b.Property<string>("PreviousHash");

                    b.Property<string>("Replies");

                    b.Property<string>("TimeStamp");

                    b.Property<string>("To");

                    b.Property<int>("Type");

                    b.Property<string>("TypeMessage");

                    b.Property<bool>("isClosed");

                    b.HasKey("Id");

                    b.ToTable("Blocks");
                });
#pragma warning restore 612, 618
        }
    }
}
